name: 作者に誤字脱字を伝える
description: 作者に誤字脱字を伝えるための issue template
title: "誤字脱字のお知らせ"
labels: [bug]
assignees:
  - pankona
body:
  - type: markdown
    attributes:
      value: |
        誤字脱字のご指摘ありがとうございます！
  - type: textarea
    id: wrong
    attributes:
      label: "どの部分に誤りがありますか？ページ数と該当箇所を教えて下さい :pray:"
    validations:
      required: true
  - type: textarea
    id: correct
    attributes:
      label: "正しくはどのようになっているべきでしょうか？ :thinking:"
    validations:
      required: true
